name: CI Pipeline

on:
  push:
    branches:
      - main # only builds when PRs are merged to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/app
          TAG=${{ github.sha }}
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
          echo "image=$IMAGE:$TAG" >> $GITHUB_OUTPUT
        id: docker

      - name: Update Dev CD repo with new image tag
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: your-org/dev-cd-repo
          event-type: update-dev-image
          client-payload: |
            {
              "image": "${{ steps.docker.outputs.image }}"
            }
